import type { Metadata } from "next";
import { KeyRound, LockKeyhole, Settings, ShieldCheck, UserRound } from "lucide-react";
import { requireWorkspace } from "@/lib/auth/tenant";
import { WorkspaceSettingsForm } from "@/components/forms/workspace-settings-form";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Settings | MessageShip" };

export default async function SettingsPage() {
  const context = await requireWorkspace();
  return <div className="space-y-8"><div><p className="text-sm font-medium text-primary">Workspace controls</p><h1 className="mt-1 font-heading text-3xl font-semibold tracking-tight">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage workspace identity and review your security posture.</p></div><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Settings className="h-4 w-4 text-primary" />Workspace profile</CardTitle><CardDescription>Update the name shown to your team.</CardDescription></CardHeader><CardContent><WorkspaceSettingsForm name={context.organization.name} /></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-4 w-4 text-primary" />Your account</CardTitle><CardDescription>Signed-in identity and workspace role.</CardDescription></CardHeader><CardContent><dl className="space-y-4 text-sm"><div><dt className="text-xs text-muted-foreground">Name</dt><dd className="mt-1 font-medium">{context.user.name}</dd></div><div><dt className="text-xs text-muted-foreground">Email</dt><dd className="mt-1 font-medium">{context.user.email}</dd></div><div><dt className="text-xs text-muted-foreground">Role</dt><dd className="mt-1"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">{context.membership.role}</span></dd></div></dl></CardContent></Card></div><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><LockKeyhole className="h-4 w-4 text-primary" />Credential encryption</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Meta and AI credentials are encrypted before database storage.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><KeyRound className="h-4 w-4 text-primary" />Scoped access</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">API keys are hashed and validated against explicit scopes.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-primary" />Audit trail</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Sensitive actions are recorded with actor, resource, and request context.</p></CardContent></Card></div></div>;
}
