"use client";

import { useActionState, useRef } from "react";
import { Loader2, Upload } from "lucide-react";
import { createContactAction, importContactsAction, previewContactsAction, type ContactActionState } from "@/app/actions/contacts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function ContactCreateForm() {
  const [state, action, pending] = useActionState<ContactActionState, FormData>(createContactAction, {});
  return <form action={action} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="contact-name">Name</Label><Input id="contact-name" name="name" placeholder="Jordan Lee" required /></div><div className="space-y-2"><Label htmlFor="contact-phone">WhatsApp number</Label><Input id="contact-phone" name="phoneNumber" placeholder="+1 555 010 2000" required /></div><div className="space-y-2"><Label htmlFor="contact-email">Email <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="contact-email" name="email" type="email" placeholder="jordan@example.com" /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="contact-tags">Tags <span className="font-normal text-muted-foreground">(comma separated)</span></Label><Input id="contact-tags" name="tags" placeholder="vip, onboarding" /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="contact-notes">Notes</Label><Textarea id="contact-notes" name="notes" placeholder="Context for your team" /></div></div>{state.error ? <p className="rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive">{state.error}</p> : null}{state.success ? <p className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-300">{state.success}</p> : null}<Button type="submit" disabled={pending}>{pending ? <Loader2 className="mr-2 animate-spin" /> : null}{pending ? "Adding…" : "Add contact"}</Button></form>;
}

export function ContactImportForm() {
  const [previewState, previewAction, previewPending] = useActionState<ContactActionState, FormData>(previewContactsAction, {});
  const [importState, importAction, importPending] = useActionState<ContactActionState, FormData>(importContactsAction, {});
  const formRef = useRef<HTMLFormElement>(null);
  return <div className="space-y-4"><form ref={formRef} action={previewAction} className="space-y-3"><div className="space-y-2"><Label htmlFor="contact-file">CSV file</Label><Input id="contact-file" name="file" type="file" accept=".csv,text/csv" required /></div><p className="text-xs text-muted-foreground">Required columns: name and phone number. Optional: email, notes, tags.</p><Button type="submit" variant="outline" disabled={previewPending}>{previewPending ? <Loader2 className="mr-2 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}{previewPending ? "Checking…" : "Preview import"}</Button></form>{previewState.error ? <p className="rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive">{previewState.error}</p> : null}{previewState.preview ? <div className="space-y-3 rounded-xl border bg-muted/30 p-4"><div className="flex gap-4 text-xs"><span><strong>{previewState.preview.validCount}</strong> ready</span><span><strong>{previewState.preview.duplicateCount}</strong> duplicates</span><span><strong>{previewState.preview.invalidCount}</strong> invalid</span></div><div className="max-h-40 overflow-y-auto rounded-lg border bg-background"><table className="w-full text-left text-xs"><thead className="border-b bg-muted/50"><tr><th className="p-2">Row</th><th className="p-2">Name</th><th className="p-2">Number</th><th className="p-2">Result</th></tr></thead><tbody>{previewState.preview.rows.slice(0, 20).map((row) => <tr key={row.row} className="border-b last:border-0"><td className="p-2">{row.row}</td><td className="p-2">{row.name ?? "—"}</td><td className="p-2">{row.phoneNumber ?? "—"}</td><td className="p-2">{row.valid ? "Ready" : row.duplicate ? "Duplicate" : row.error}</td></tr>)}</tbody></table></div><form action={importAction}><input type="hidden" name="file" value="" /><Button type="button" disabled={!previewState.preview.validCount} onClick={() => { const file = formRef.current?.querySelector<HTMLInputElement>('input[type="file"]')?.files?.[0]; if (file) { const form = new FormData(); form.append("file", file); void importAction(form); } }}>{importPending ? <Loader2 className="mr-2 animate-spin" /> : null}{importPending ? "Importing…" : `Import ${previewState.preview.validCount} contacts`}</Button></form></div> : null}{importState.success ? <p className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-700 dark:text-emerald-300">{importState.success}</p> : null}{importState.error ? <p className="rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive">{importState.error}</p> : null}</div>;
}
